# Generated by Django 5.1.6 on 2025-02-08 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('hour_available', models.CharField(choices=[('1', 'Hour 1'), ('2', 'Hour 2'), ('both', 'Both Hours')], max_length=10)),
                ('max_assignments', models.IntegerField(default=6)),
                ('current_assignments', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('advisor_first_name', models.CharField(max_length=50)),
                ('advisor_last_name', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JudgeExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(blank=True, null=True)),
                ('judge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poster_assignment.judge')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('1', 'Hour 1'), ('2', 'Hour 2')], max_length=10)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poster_assignment.judge')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poster_assignment.poster')),
            ],
        ),
    ]
