# Generated by Django 5.1.6 on 2025-02-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
