# Generated by Django 5.1.6 on 2025-02-08 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_assignment', '0002_judge_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgeexpertise',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poster_assignment.judge'),
        ),
        migrations.AlterField(
            model_name='judgeexpertise',
            name='keywords',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
