# Generated by Django 5.1.6 on 2025-02-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_assignment', '0003_alter_judgeexpertise_judge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgeexpertise',
            name='judge',
        ),
        migrations.AddField(
            model_name='judgeexpertise',
            name='judge_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
