# Generated by Django 5.1.6 on 2025-02-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_assignment', '0004_remove_judgeexpertise_judge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='assigned_judge_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='poster',
            name='assigned_judge_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
