# Generated by Django 5.1.6 on 2025-02-09 00:07

import poster_assignment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_assignment', '0005_poster_assigned_judge_1_poster_assigned_judge_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='password',
            field=models.CharField(default=poster_assignment.models.generate_random_password, editable=False, max_length=8),
        ),
    ]
