# Generated by Django 5.1.6 on 2025-02-09 00:09

import poster_assignment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_assignment', '0006_judge_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='password',
            field=models.CharField(blank=True, default=poster_assignment.models.generate_random_password, max_length=8, null=True),
        ),
    ]
