# Generated by Django 5.1.6 on 2025-02-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_assignment', '0007_alter_judge_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='password',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
