# Generated by Django 5.1.6 on 2025-02-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_assignment', '0008_alter_judge_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='judge_1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poster',
            name='judge_2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
