# Generated by Django 5.1.6 on 2025-02-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_assignment', '0009_poster_judge_1_score_poster_judge_2_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='judge_1_score',
            new_name='judge_1_creativity',
        ),
        migrations.RenameField(
            model_name='poster',
            old_name='judge_2_score',
            new_name='judge_1_implementation',
        ),
        migrations.AddField(
            model_name='poster',
            name='judge_1_innovation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poster',
            name='judge_2_creativity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poster',
            name='judge_2_implementation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poster',
            name='judge_2_innovation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
